/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.sauces.gui;

/**
 *
 * @author Alex
 */
public class CrearCuenta extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CODIGO = new javax.swing.JLabel();
        TITULAR = new javax.swing.JLabel();
        SALDO = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        TitularText = new javax.swing.JTextField();
        SaldoText = new javax.swing.JTextField();
        AceptarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        CODIGO.setForeground(new java.awt.Color(0, 0, 0));
        CODIGO.setText("CÓDIGO");

        TITULAR.setForeground(new java.awt.Color(0, 0, 0));
        TITULAR.setText("TITULAR");

        SALDO.setForeground(new java.awt.Color(0, 0, 0));
        SALDO.setText("SALDO");

        codigoText.setBackground(new java.awt.Color(255, 255, 255));
        codigoText.setForeground(new java.awt.Color(255, 255, 255));

        TitularText.setBackground(new java.awt.Color(255, 255, 255));
        TitularText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitularTextActionPerformed(evt);
            }
        });

        SaldoText.setBackground(new java.awt.Color(255, 255, 255));

        AceptarBoton.setBackground(new java.awt.Color(204, 204, 204));
        AceptarBoton.setForeground(new java.awt.Color(204, 204, 255));
        AceptarBoton.setText("ACEPTAR");
        AceptarBoton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBotonActionPerformed(evt);
            }
        });

        CancelarBoton.setBackground(new java.awt.Color(204, 204, 204));
        CancelarBoton.setForeground(new java.awt.Color(0, 0, 0));
        CancelarBoton.setText("CANCELAR");
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SALDO)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TITULAR)
                        .addComponent(CODIGO)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitularText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaldoText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(AceptarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelarBoton)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CODIGO)
                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitularText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TITULAR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SALDO)
                    .addComponent(SaldoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarBoton)
                    .addComponent(CancelarBoton))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void TitularTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitularTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitularTextActionPerformed

    private void AceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBoton;
    private javax.swing.JLabel CODIGO;
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JLabel SALDO;
    private javax.swing.JTextField SaldoText;
    private javax.swing.JLabel TITULAR;
    private javax.swing.JTextField TitularText;
    private javax.swing.JTextField codigoText;
    // End of variables declaration//GEN-END:variables
}
